config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'careers', to: 'static_pages#careers'
  get 'team', to: 'static_pages#team'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def cost_in_cents
    (cost * 100).to_i
  end

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel

  ranks :row_order, with_same: :section_id

  def send_lesson_email
    NotificationMailer.lesson_added(self).deliver_later
  end

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first

    if lesson.blank? && section.next_section.present?
      return section.next_section.lessons.rank(:row_order).first
    end

    return lesson
  end

  def previous_lesson
    lesson = section.lessons.where("row_order < ?", self.row_order).rank(:row_order).last

    if lesson.blank? && section.previous_section.present?
      return section.previous_section.lessons.rank(:row_order).last
    end

    return lesson
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons

  include RankedModel

  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end

  def previous_section
    section = course.sections.where("row_order < ?", self.row_order).rank(:row_order).first
    return section
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    enrolled_courses.include?(course)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  helper_method :current_course, :current_lesson, :current_section

  def current_course
    id = params.key?(:course_id) ? params[:course_id] : params[:id]
    @current_course ||= Course.find(id)
  end

  def current_lesson
    id = params.key?(:lesson_id) ? params[:lesson_id] : params[:id]
    @current_lesson ||= Lesson.find(id)
  end

  def current_section
    id = params.key?(:section_id) ? params[:section_id] : params[:id]
    @current_section ||= Section.find(id)
  end

  def require_authorized_for_current_section
    return if current_section.course.user == current_user
    render plain: 'Unauthorized', status: :unauthorized
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show

  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create

    if current_course.premium?
      # Amount in cents
      @amount = current_course.cost_in_cents

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Paid Content',
        currency: 'usd'
      )
    end

    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to course_path(current_course)
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]

  def create
    @lesson = current_section.lessons.create(lesson_params)
    @lesson.send_lesson_email
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated!'
  end

  private

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end

  def require_authorized_for_current_lesson
    return if current_lesson.section.course.user == current_user
    render plain: 'Unauthorized', status: :unauthorized
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render plain: 'updated!'
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrolled_for_current_lesson

  def show
  end

  private

  def require_enrolled_for_current_lesson
    course = current_lesson.section.course
    unless current_user.enrolled_in?(course)
      redirect_to course_path(course), alert: "You need to be enrolled in \"#{course.title}\" to view its lesson \"#{current_lesson.title}\" "
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def privacy
  end

  def careers
  end

  def team
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />
  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    <br>
    <% if course.image.present? %>
      <div class="row">
        <div class="col-12 text-center">
          <%= image_tag course.image, class: 'img-fluid course-image rounded' %>
        </div>
      </div>
    <% end %>
    <div class="row text-center">
      <div class="col-sm-7 col-12">
        <%= course.description %>
      </div>
      <div class="col-sm-4 col-12">
        <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br>
    <br>
    <hr class="col-8 offset-2">
  <% end %>
</div>

app/views/courses/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <% if current_course.image.present? %>
    <div class="col-12 text-center">
      <%= image_tag current_course.image, class: 'img-fluid course-image rounded' %>
    </div>
  <% end %>

  <div class="row course-info">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <% if current_course.free? %>
          Free Course!
        <% else %>
          <%= number_to_currency current_course.cost %>
        <% end %>
      </span>

      <% if current_user %>
        <% if current_user == current_course.user %>
          <br>
          <br>
          <%= link_to 'Administer', instructor_course_path(current_course), class: 'btn btn-danger btn-large' %>
        <% end %>
        <br>
        <br>
        <% if current_user.enrolled_in?(current_course) %>
          <h2 class="badge badge-info">You Are Enrolled!</h2>
        <% else %>
          <% if current_course.premium? %>
            <%= form_tag course_enrollments_path(current_course) do %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-email="<%= current_user.email %>"
                      data-description="<%= current_course.title %>: <%= number_to_currency current_course.cost %>"
                      data-amount="<%= current_course.cost_in_cents %>"
                      data-locale="auto"></script>
            <% end %>
          <% else %>
            <%= link_to 'Enroll', course_enrollments_path(current_course), class: 'btn btn-primary', method: :post %>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to 'Sign In to Enroll!', new_user_session_path, class: 'btn btn-success' %>
      <% end %>
      <span class="clearfix"></span>
    </div>

    <div class="col-sm-8 col-12">
      <%= current_course.description %>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <% current_course.sections.rank(:row_order).each do |section| %>
        <div class="sections row">
          <h3 class= "col-12"><%= section.title %></h3>
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <div class="lesson col-12 col-sm-6">
              <div class="d-flex justify-content-center align-items-center text-center lesson-details">
                <%= link_to lesson_path(lesson) do %>
                  <b><%= lesson.title %></b>
                  <br>
                  <%= lesson.subtitle %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image, label: 'Add an image!' %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.new-lesson-button').click(function() {
      var lessonUrl = ( $(event.target).data('lesson-url') );
      $('#newLessonForm').attr('action', lessonUrl);
    });

    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>

<!-- content -->
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <% if current_course.image.present? %>
    <div class="col-12 text-center">
      <%= image_tag current_course.image, class: 'img-fluid course-image rounded' %>
    </div>
  <% end %>
  <div class="col-12 col-sm-6 offset-sm-6 d-sm-flex justify-content-sm-end flex-wrap">
    <%= link_to 'Preview As Student', course_path(current_course), class: 'btn btn-warning mb-2 col-12 col-sm-10' %>
    <button type="button" class="btn btn-primary col-12 col-sm-10" data-toggle="modal" data-target="#newSectionModal">
      Add a new section
    </button>
  </div>
  <ul class="sections m-md-4">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li data-update-url=<%= instructor_section_path(section)%>>

        <div class="header grab-cursor">
          <%= fa_icon "ellipsis-v" %>
          <%= section.title %>
          <button
            type="button"
            class="float-right btn btn-primary btn-sm new-lesson-button"
            data-toggle="modal"
            data-target="#newLessonModal"
            data-lesson-url="<%= instructor_section_lessons_path(section) %>">
              Add a new lesson
          </button>
          <span class="clearfix"></span>
        </div>

        <ul class="lessons d-sm-flex flex-sm-wrap justify-content-sm-end">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url=<%= instructor_lesson_path(lesson) %> class="col-12 col-sm-11 grab-cursor">
              <div class="d-flex justify-content-between align-items-center">
                <%= fa_icon "ellipsis-v" %>
                <div class="text-center">
                  <p>
                    <b><%= lesson.title %></b>
                  </p>
                  <p>
                    <%= lesson.subtitle %>
                  </p>
                </div>
                <span class="clearfix"></span>
              </div>
            </li>
          <% end %>
        </ul>
        <span class="clearfix"></span>
      </li>
    <% end %>
  </ul>
</div>

<!-- Add Section Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="newSectionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="newSectionModalLabel"><i>Add a New Section</i></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add a section", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Add Lesson Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="newLessonModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="newLessonModalLabel"><i>Add a New Lesson</i></h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @lesson, url: '#', html: { id: 'newLessonForm' } do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add a lesson", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="booyah-box col-10 offset-1">
  <div class="col-12 text-center">
    <h1>
      <%= link_to current_lesson.section.course.title, course_path(current_lesson.section.course) %>
    </h1>
    <h2 class="skinny-title"><%= current_lesson.section.title %></h2>
  </div>
  <hr>
  <h2><%= current_lesson.title %></h2>
  <p class="pl-3">
    <%= current_lesson.subtitle %>
  </p>

  <div class="col-12">
    <% if current_lesson.previous_lesson.present? %>
      <%= link_to lesson_path(current_lesson.previous_lesson), class: "btn btn-default float-left" do %>
        <span class="fa fa-backward"></span>
        &nbsp; Previous Lesson
      <% end %>
    <% end %>

    <% if current_lesson.next_lesson.present? %>
      <%= link_to lesson_path(current_lesson.next_lesson), class: "btn btn-default float-right" do %>
        Next Lesson &nbsp;
        <span class="fa fa-forward"></span>
      <% end %>
    <% end %>
    <span class="clearfix"></span>
  </div>

  <% if current_lesson.video.present? %>
    <video id="my-video" class="col-12 my-1 video-js vjs-big-play-centered vjs-fluid" controls preload="auto" poster="<%= image_path('poster.png') %>" data-setup="{}">
      <source src="<%= current_lesson.video.to_s %>" type="video/mp4">
      <noscript>
        <p class="vjs-no-js">
          To view this video please enable JavaScript, and consider upgrading to a web browser that
          <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
      </noscript>
    </video>
  <% else %>
    <div class="col-12 text-center my-5">
      <p>
        There is no video available for this lesson.
      </p>
    </div>
  <% end %>
</div>