config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'careers', to: 'static_pages#careers'
  get 'team', to: 'static_pages#team'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def cost_in_cents
    (cost * 100).to_i
  end

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel

  ranks :row_order, with_same: :section_id

  def send_lesson_email
    NotificationMailer.lesson_added(self).deliver_later
  end

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first

    if lesson.blank? && section.next_section.present?
      return section.next_section.lessons.rank(:row_order).first
    end

    return lesson
  end

  def previous_lesson
    lesson = section.lessons.where("row_order < ?", self.row_order).rank(:row_order).last

    if lesson.blank? && section.previous_section.present?
      return section.previous_section.lessons.rank(:row_order).last
    end

    return lesson
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons

  include RankedModel

  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end

  def previous_section
    section = course.sections.where("row_order < ?", self.row_order).rank(:row_order).first
    return section
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    enrolled_courses.include?(course)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  helper_method :current_course, :current_lesson, :current_section

  def current_course
    id = params.key?(:course_id) ? params[:course_id] : params[:id]
    @current_course ||= Course.find(id)
  end

  def current_lesson
    id = params.key?(:lesson_id) ? params[:lesson_id] : params[:id]
    @current_lesson ||= Lesson.find(id)
  end

  def current_section
    id = params.key?(:section_id) ? params[:section_id] : params[:id]
    @current_section ||= Section.find(id)
  end

  def require_authorized_for_current_section
    return if current_section.course.user == current_user
    render plain: 'Unauthorized', status: :unauthorized
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show

  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create

    if current_course.premium?
      # Amount in cents
      @amount = current_course.cost_in_cents

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flixter Paid Content',
        currency: 'usd'
      )
    end

    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to course_path(current_course)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrolled_for_current_lesson

  def show
  end

  private

  def require_enrolled_for_current_lesson
    course = current_lesson.section.course
    unless current_user.enrolled_in?(course)
      redirect_to course_path(course), alert: "You need to be enrolled in \"#{course.title}\" to view its lesson \"#{current_lesson.title}\" "
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def privacy
  end

  def careers
  end

  def team
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://vjs.zencdn.net/6.6.3/video-js.css" rel="stylesheet">
  </head>

  <body>
    <div id="flex-content-container">
      <nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
        <%= link_to "<h1>Flixter</h1>".html_safe, root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainNavContent" aria-controls="mainNavContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="mainNavContent">
          <div class="navbar-nav justify-content-start">
            <%= link_to "See All Courses", courses_path, class: "nav-item nav-link" %>
          </div>
          <div class="dropdown-divider"></div>
          <div class="navbar-nav justify-content-end">
            <% if user_signed_in? %>
              <%= link_to 'My Dashboard', dashboard_path, class: 'nav-link nav-item' %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link nav-item' %>
            <% else %>
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link nav-item' %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link nav-item' %>
            <% end %>
          </div>
        </div>
      </nav>
      <div class="container-fluid">
        <% if notice.present? %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>

        <% if alert.present? %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>

        <% if flash[:error].present? %>
          <div class="col-10 offset-1 alert alert-danger text-center">
            <%= flash[:error] %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-3">
            <b>Teachers</b>
            <br>
            <%= link_to 'Teach a Course', new_instructor_course_path %>
            <br>
            <%= link_to 'My Dashboard', dashboard_path %>
          </div>
          <div class="col-12 col-sm-3">
            <b>About</b>
            <br>
            <%= link_to 'Team', team_path %>
            <br>
            <%= link_to 'Careers', careers_path %>
            <br>
            <%= link_to 'Privacy Policy', privacy_path %>
          </div>
          <div class="col-12 col-sm-3">
            <b>Contact</b>
            <br>
              <%= mail_to 'bkautt@gmail.com' %>
          </div>
          <div class="col-12 col-sm-3">
            <b>Social</b>
            <br>
            <%= link_to 'https://github.com/tallKitties', target: "_blank" do %>
              <span class="fa fa-github fa-lg m-1"></span>
            <% end %>
            <%= link_to 'https://www.linkedin.com/in/benkautt/', target: "_blank" do %>
              <span class="fa fa-linkedin fa-lg m-1"></span>
            <% end %>
            <%= link_to 'https://www.instagram.com/tallkitties/', target: "_blank" do %>
              <span class="fa fa-instagram fa-lg m-1"></span>
            <% end %>
          </div>
      </div>
    </div>
    <script src="https://vjs.zencdn.net/6.6.3/video.js"></script>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  </body>
</html>